{% set name = "mudirac" %}
{% set version = "1.1.1" %}


package:
  name: mudirac
  version: {{ version }}

source:
  url: https://github.com/muon-spectroscopy-computational-project/mudirac/archive/refs/tags/{{ version }}.tar.gz
  sha256: d1ae58f138c18c6f515ac08267608054f89d85ac5564d2587b18363f1f634823

build:
  number: 0
  skip: true  # [win]
  skip: true  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make

test:
  commands: mudirac --help

about:
  home: https://muon-spectroscopy-computational-project.github.io/mudirac/
  summary: 'Simulation software that integrates the Dirac equation for muonic atoms to compute their X-Ray transition energies.'
  description: |
    MuDirac is a simulation software that integrates the Dirac equation for muonic atoms to compute their X-Ray transition energies;
    it is written in C++.  The use and functioning of MuDirac 1.0 is extensively documented in the paper [S. Sturniolo, A. Hillier, 
    “Mudirac: A Dirac equation solver for elemental analysis with muonic X-rays”, X-Ray Spectrom. 2020;1–17](https://onlinelibrary.wiley.com/doi/full/10.1002/xrs.3212),
    which should be cited by any work using it.

  license: MIT
  license_file: LICENSE
  doc_url: https://muon-spectroscopy-computational-project.github.io/mudirac/
  dev_url: https://github.com/muon-spectroscopy-computational-project/mudirac

extra:
  recipe-maintainers:
    - subindev-d
    - patrick-austin
